version: '3.8'
services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: polimarket  # Cambia el nombre de la base de datos según tus necesidades
      MYSQL_ROOT_PASSWORD: P@ssw0rd  # Cambia esta contraseña según sea necesario
    ports:
      - "3306:3306"  # Puerto de la base de datos

  webapp:
    build:
      context: .
      dockerfile: Dockerfile  # Especificamos el Dockerfile en la raíz del proyecto
    container_name: webapp
    ports:
      - "8080:8080"  # Puerto de la aplicación
    depends_on:
      - database  # Asegura que la base de datos se inicie antes de la aplicación
