version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polimarket-web
    ports:
      - "8080:8080"
    volumes:
      - ./db:/usr/local/tomcat/db
